[package]
name = "ci_tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
anyhow.workspace = true
strip-ansi-escapes = "0.2.1"
