[package]
name = "mvr-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
sui-field-count = { git = "https://github.com/MystenLabs/sui.git"}
diesel = { workspace = true, features = ["postgres", "uuid", "chrono", "serde_json", "numeric"] }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
