[package]
name = "nftmaker"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
ToDoReplaceWithDependencyName = { r.mvr = "@mvr-tst/first-app" }

[addresses]
nftmaker = "0x0"

[r.mvr]
network = "mainnet"
