name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isRust:
    description: True when changes happened to the Rust code
    value: "${{ steps.diff.outputs.isRust }}"

runs:
  using: composite
  steps:
  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
  - name: Detect Changes
    uses: dorny/paths-filter@v3
    id: diff
    with:
      filters: |
        isRust:
          - 'crates/**'
          - '.github/workflows/rust-ci.yml'
          - 'Cargo.lock'
          - 'Cargo.toml'
