// Example trust config — what a populated production `CHECKED_IN_CONFIG`
// (`app/src/lib/attestations.ts`) looks like once attesters are onboarded.
//
// This is a reviewer-facing reference, not wired into the app: the production
// list lives in `CHECKED_IN_CONFIG` and the demo injects the same shape as JSON
// via `NEXT_PUBLIC_ATTESTATION_CONFIG` (generated by `scripts/write-demo-env.sh`).
// Serialize this object to JSON and you have exactly the env-var form.
//
// All ids below are illustrative placeholders — replace with real on-chain ids.
// Trust is a *consumer* decision keyed by package address: listing an attester
// here means "I trust attestations whose inner type is defined by this package."

import type { AttestationConfig } from "./attestations";

export const EXAMPLE_ATTESTATION_CONFIG: AttestationConfig = {
  // The `attestations` base-registry package id — the `Attestation<>` wrapper's
  // defining package (used to match the on-chain object type).
  registryPkg: "0x1111111111111111111111111111111111111111111111111111111111111111",
  // The shared Registry object id — the parent for per-subject Box derivation.
  registryId: "0x2222222222222222222222222222222222222222222222222222222222222222",

  trustedAttestors: [
    {
      // Shown as the attester heading in the UI.
      name: "Example Auditor",
      // Brand icon, hosted by the attester (never read from on-chain data).
      // Absent → the UI renders an initials avatar instead.
      iconUrl: "https://example-auditor.com/icon.svg",
      // Optional: links the attester heading to its MVR package page.
      mvrName: "@example-auditor/audits",
      // The attester package's *original* publish id — the trust anchor.
      originalId: "0xaaaa000000000000000000000000000000000000000000000000000000000000",
      // Every version id in the attester's lineage (original publish + each
      // upgrade). An attestation counts as from this attester when its inner
      // type's defining package is in this set — so attestation types added in
      // later upgrades stay trusted automatically.
      lineage: [
        "0xaaaa000000000000000000000000000000000000000000000000000000000000",
        "0xaaaa111111111111111111111111111111111111111111111111111111111111",
      ],
    },
    {
      // A second attester with no icon (renders an initials avatar) and no MVR
      // page, and a single-version lineage (never upgraded).
      name: "Example Security Scanner",
      originalId: "0xbbbb000000000000000000000000000000000000000000000000000000000000",
      lineage: [
        "0xbbbb000000000000000000000000000000000000000000000000000000000000",
      ],
    },
  ],
};
