import { PlainPageLayout } from "@/components/layouts/PlainPageLayout";
import { Text } from "@/components/ui/Text";


const TERMS_CONTENT = `<p><strong>Terms of Service</strong></p>
<p>Welcome to the Move Registry 👋</p>
<p>Effective Date: December 15, 2024</p>
<p>These Terms of Service (“<u>Terms</u>”) govern your use of the website&nbsp;located at [URL] (the&nbsp;“<u>Website</u>”), owned and operated by the Sui Foundation (referred to as “<u>Foundation</u>”, “<u>we</u>”, or “<u>us</u>”). The Website, and the products and services, including the Move Registry accessible via the Website are collectively referred to as the “<u>Services</u>.” By accessing or using the Website, the Move Registry and any associated Services, you agree to and accept these Terms. You are responsible for ensuring compliance with all applicable laws and regulations when using the Services.&nbsp;If you don’t agree to be bound by these Terms, do not use the Services.</p>
<p>IMPORTANT NOTICE REGARDING ARBITRATION: WHEN YOU AGREE TO THESE TERMS YOU ARE AGREEING (WITH LIMITED EXCEPTION) TO RESOLVE ANY DISPUTE BETWEEN YOU AND THE FOUNDATION THROUGH BINDING, INDIVIDUAL ARBITRATION RATHER THAN IN COURT. PLEASE REVIEW CAREFULLY SECTION XVI “DISPUTE RESOLUTION” BELOW FOR DETAILS REGARDING ARBITRATION.</p>
<ol>
    <li><strong>Eligibility</strong>.&nbsp;</li>
</ol>
<p>You may use the Services only if you are 18 years or older and capable of forming a binding contract with the Foundation, and not otherwise barred from using the Services under applicable law. You agree that your access and use of the Website fully complies with all applicable laws and regulations in your jurisdiction, and that you will not access or use the Website to conduct, promote, or otherwise facilitate any illegal activities.</p>
<ol start="2">
    <li><strong>Privacy Policy</strong>.&nbsp;</li>
</ol>
<p>Please review our Privacy Policy, which also governs your use of the Services, for information on how we collect, use and share your information. By using the Services, you agree to be bound by our Privacy Policy.</p>
<ol start="3">
    <li><strong>Provision of Services</strong>
        <ol>
            <li><u>Move Registry</u>. The Move Registry is a blockchain-based registration system designed to enable developers to reference Move packages using easily identifiable names instead of cryptographic addresses, simplifying development and enhancing cross-network interoperability. The Move Registry allows users to register their Move packages with human-readable names ending in “.move” (“<u>Human Readable Names</u>”) and associate them with existing “.sui” names registered with the Sui Name Service protocol (the “<u>SuiNS Protocol</u>”). Users may use the Services to access and interact with the Move Registry, including to register, search, and manage the Move Registry and their associated Move package addresses. </li>
            <li><u>SuiNS Protocol</u>. Although the Move Registry utilizes the SuiNS Protocol and its underlying decentralized Sui blockchain network, neither the Foundation nor its associated entities provide, own, or control the SuiNS Protocol, which is entirely run by smart contracts deployed on the Sui blockchain. Upgrades and modifications to the SuiNS Protocol are determined by its community’s self-governance processes, as may be in effect from time to time. We disclaim any liability for any issues arising from the use or operation of the Sui blockchain or the SuiNS Protocol, including but not limited to delays, losses, malfunctions, or other damages. </li>
            <li><u>Move Package Registration</u>. Users using the Move Registry are responsible for ensuring the accuracy and completeness of the SuiNS Protocol name, Human Readable Names and Move package information that they provide. Any information submitted to the Registry and recorded on the blockchain is immutable upon registration and may not be modified. In addition, you are solely responsible for uploading, providing and maintaining the availability, security and useability of any Move packages. Neither the Foundation nor any third parties shall be responsible for the availability, useability, security or content associated with any Move packages that you use in connection with the Move Registry.</li>
            <li><u>Registration and Renewal of SuiNS Protocol Names</u>. While Human Readable Names recorded on the blockchain are immutable and do not expire, names registered on the SuiNS Protocol require registration, maintenance and periodic renewals, and it is solely your responsibility to monitor and renew your registrations. If a SuiNS Protocol name expires, the name may become available for registration by other users, potentially resulting in the loss of the link between your SuiNS Protocol name and any associated Move packages. It is solely your responsibility to ensure timely renewal, maintenance and security of your SuiNS Protocol names to prevent the potential loss of ownership or link disruption to the Move Registry. IN THE EVENT THAT YOU FAIL TO PROPERLY MAINTAIN, RENEW OR SECURE REGISTRATION OF YOUR SUINS PROTOCOL NAMES, YOU AND ANY THIRD PARTIES OR SOFTWARE PROTOCOLS INTERACTING WITH YOUR SUINS PROTOCOL NAMES, MOVE PACKAGES, OR THE MOVE REGISTRY, MAY IRRETRIEVABLY LOSE THE ABILITY TO CONNECT WITH, REGISTER, UPDATE, RETRIEVE AND USE THE MOVE REGISTRY AND THE INFORMATION CONTAINED THEREIN. The Foundation and its associated entities cannot forcibly remove, prevent, renew, or interfere with the ability of any person to register a name on the SuiNS Protocol's registry once it has expired. As a result, the Foundation disclaims any liability for your inability to use, register, or renew any name on the SuiNS Protocol or the associated consequences to the Move Registry resulting thereof. You agree not to hold the Foundation liable for any claims, damages, or losses associated with the expiration of a SuiNS Protocol name, including the loss of any link between a Move package and your SuiNS Protocol name. </li>
            <li><u>Non-Custodial Nature</u>.The Website is a non-custodial application, meaning you are solely responsible for the custody of your cryptographic private keys to the digital asset wallets you hold, as well as the instructions and transactions that you engage in using your cryptographic private keys and digital asset wallets. These Terms do not create or impose any duties on the Foundation. To the fullest extent permitted by law, you acknowledge and agree that the Foundation owes no fiduciary duties or liabilities to you or any other party, and that any such duties or liabilities that may exist at law or in equity are hereby irrevocably disclaimed, waived, and foregone. The only duties and obligations owed to you by the Foundation are those explicitly set out in these Terms.</li>
            <li><u>Wallet Security</u>. Users are encouraged to use hardware wallets or other secure methods to manage their cryptographic keys, including in connection with Move Registry registrations. You are solely responsible for ensuring the security of your wallet and private keys. If you lose access to your wallet or your keys are compromised, the Foundation cannot recover your assets or associated Move Registry registrations. It is recommended that you regularly back up your private keys in a secure environment and avoid sharing sensitive information related to wallet access.</li>
            <li><u>Service Fees</u>. In addition to blockchain gas fees, users may incur fees for interacting with the Move Registry, such as to register Move packages. From time to time, the Foundation may charge fees for utilizing the Services, and users are responsible for reviewing the latest fee structure before engaging in transactions.</li>
            <li><u>Variable Costs and Transaction Speeds</u>. You will be required to pay any and all fees associated with using the Move Registry, including gas and transaction fees. You acknowledge and accept that the cost and speed of transacting with cryptographic and blockchain-based systems, including the Sui blockchain and the SuiNS Protocol, are variable and may fluctuate dramatically. The Foundation is not responsible for any increased costs or delays associated with your transactions on the SuiNS Protocol.</li>
            <li><u>Non-Refundability</u>. Once a Move package is associated with a SuiNS Protocol name via the Move Registry, the related gas fees and any other related fees are non-refundable. All transactions executed by the Services on the blockchain are final and irreversible. </li>
        </ol>
    </li>
</ol>
<ol start="4">
    <li><strong>Third-Party Resources and Promotions</strong>.The Website may include references or links to third-party resources, including information, materials, products, or services that are not owned or controlled by the Foundation. Additionally, third parties may offer promotions related to your access and use of the Website. The Foundation does not endorse or assume any responsibility for any such resources or promotions. If you access these resources or participate in these promotions, you do so at your own risk, and these Terms do not apply to your dealings with third parties. You expressly release the Foundation from any liability arising from your use of third-party resources or participation in third-party promotions.</li>
</ol>
<ol start="5">
    <li><strong>Intellectual Property Rights</strong>. The intellectual property (“<u>IP</u>”) associated with the Website, including but not limited to its contents, text, software, code, scripts, webpages, graphical user interface, photographs, video, graphics, or other material, is intended for your personal and non-commercial use only. You may not use, modify, reproduce, republish, upload, post, transmit, perform, license, or distribute the IP of the Website in any way without the prior written permission of the Foundation. Any unauthorized use of the Website’s IP will constitute a violation of the Foundation's or third parties’ intellectual property rights. To use any part of the Website’s contents beyond personal and non-commercial use, you must first obtain the express written permission from the Foundation or the relevant third party. The Foundation reserves the right to refuse permission without providing any reasons. </li>
</ol>
<ol start="6">
    <li><strong>Ownership</strong>. We reserve all rights not expressly granted to you in these Terms. The Services are protected by copyright, trademark, patent, and other laws of the United States and other countries. We own all rights, title, interest in and to the Services and all copies of the Services. These Terms do not grant you any rights to our trademarks or service marks. You may submit feedback, comments, or ideas about the Services (“<u>Ideas</u>”). Submitting Ideas is entirely voluntary, and we will be free to use such Ideas as we see fit and without any restrictions or obligation to you.</li>
    <li><strong>Your Content</strong>.<ol>
            <li><u>Linked Content</u>. The Services allow you to associate your SuiNS Protocol name with Move packages via the Move Registry. We refer to all content linked via the Move Registry as “<u>Linked Content</u>”. The Foundation does not claim any ownership rights in any Linked Content and nothing in these Terms will be deemed to restrict any rights that you may have to your Linked Content. You are solely responsible for your Linked Content.</li>
            <li><u>Permissions to Your Linked Content</u>. By making any Linked Content available through the Services you hereby grant to the Foundation a non-exclusive, transferable, worldwide, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works based upon, distribute, publicly display, and publicly perform your Linked Content in connection with operating and providing the Services.</li>
            <li><u>Your Responsibility for Linked Content</u>. You are solely responsible for all your Linked Content. You represent and warrant that you have (and will maintain) all rights that are necessary to grant us the license rights in your Linked Content under these Terms. You represent and warrant that neither your Linked Content, nor your use and provision of your Linked Content to be made available through the Services, nor any use of your Linked Content by the Foundation on or through the Services will infringe, misappropriate or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation. </li>
            <li><u>Removal of Linked Content</u>. Any information recorded on the Move Registry is publicly available and immutable, and may not be completely removed. To the maximum extent permitted by law, we are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any of your Linked Content. You agree to remove or disable access to any content, including Linked Content, at any time and without notice, in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</li>
        </ol>
    </li>
    <li><strong>DMCA/Copyright Policy</strong>. The Foundation respects copyright law and expects its users to do the same. It is the Foundation’s policy to terminate, in appropriate circumstances, users who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders. </li>
</ol>
<ol start="9">
    <li><strong>Use of Website.</strong>&nbsp;You must not do or attempt to do anything of the following, or use the Website to do any of the following, without our prior written consent:<ol>
            <li>use the Website in any manner that could damage, disable, overburden or impair any service provided via or function of the Website (or the network(s) connected to the Website) or interfere with any other party's use or enjoyment of any such service or the Website;</li>
            <li>access the Website from a different blockchain address if we have blocked any of your other blockchain addresses from accessing the Website unless you have our written permission first;</li>
            <li>gain unauthorised access to the Website, other computer systems or networks connected to the Website, or our internal and external servers through hacking, password mining or any other means;</li>
            <li>obtain or attempt to obtain any materials, content or data through any means not intentionally made available through the Website;</li>
            <li>manipulate any content on the Website by way of hacking, backdoor code insertion, or any other means;</li>
            <li>decompile, reverse engineer or disassemble our Website;</li>
            <li>infringe or misappropriate our intellectual property rights or the intellectual property rights of any person;</li>
            <li>use our Website in any manner that could negatively affect or is prejudicial to our reputation;</li>
            <li>use our Website or the Services provided for or in connection with money laundering, terrorist financing, or other illicit financial activity, or in any way in connection with the violation of any law or regulation that applies to you or to us;</li>
            <li>use our Website, or Services provided by us directly or indirectly, for, on behalf of, or for the benefit of any natural or legal person that is (i) the subject of sanctions (as described in Section X), or (ii) citizen of, located in, resident in, or organized under the laws of, any jurisdiction that has been designated as non-cooperative with international anti-money laundering principles or procedures by an intergovernmental group or organization, such as the Financial Action Task Force, or subject of sanctions; </li>
            <li>use our Website in any manner or for any purpose that is unlawful or prohibited by these Terms or any other notices and conditions that the Foundation may issue from time to time; or</li>
            <li>Register or associate any SuiNS Protocol names with any Move package that: <ol>
                    <li>is unlawful or promotes unlawful activities, incurring legal liability in the countries the Foundation officially operates in;</li>
                    <li>is libelous, defamatory, or fraudulent;</li>
                    <li>amounts to phishing or attempted phishing;</li>
                    <li>unlawfully shares unauthorized product licensing keys, software for generating unauthorized product licensing keys, or software for bypassing checks for product licensing keys, including extension of a free license beyond its trial period;</li>
                    <li>contains malicious code, such as computer viruses, computer worms, rootkits, back doors, or spyware, including content submitted for research purposes (tools designed and documented explicitly to assist in security research are acceptable, but exploits and malware that use the Move registry as a deployment or delivery vector are not); </li>
                    <li>uses obfuscation to hide or mask functionality;</li>
                    <li>is discriminatory toward, harasses or abuses another individual or group;</li>
                    <li>threatens or incites violence toward any individual or group, especially on the basis of who they are;</li>
                    <li>is using the Move Registry as a platform for propagating abuse on other platforms;</li>
                    <li>violates the privacy of any third party, such as by posting another person's personal information without consent;</li>
                    <li>gratuitously depicts or glorifies violence, including violent images;</li>
                    <li>is sexually obscene or relates to sexual exploitation or abuse, including of minors;</li>
                    <li>is off-topic, or interacts with platform features in a way that significantly or repeatedly disrupts the experience of other users;</li>
                    <li>exists only to reserve a Human Readable Name for a prolonged period of time (often called "name squatting") without having any genuine functionality, purpose, or significant development activity on the corresponding repository;</li>
                    <li>impersonates any person or entity, including through false association with the Move Registry, or by fraudulently misrepresenting your identity or site's purpose;</li>
                    <li>is related to inauthentic interactions, such as fake accounts and automated inauthentic activity;</li>
                    <li>is using our servers for any form of excessive automated bulk activity, to place undue burden on our servers through automated means, or to relay any form of unsolicited advertising or solicitation through our servers, such as get-rich-quick schemes; or</li>
                    <li>is not functionally compatible with the Move Registry.</li>
                </ol>
            </li>
        </ol>
    </li>
</ol>
<ol start="10">
    <li><strong>Sanctions</strong>. Without limiting the foregoing, you may not, directly or indirectly, access or use the Services if (i) you are in, under the control of, or a national or resident of Cuba, Iran, North Korea, Syria, the Crimea, Sevastopol, Luhansk and Donetsk regions of Ukraine or any other jurisdiction subject to United States embargo, or if you are listed on any sanctions asset blocking list or export denial list maintained by the US, EU, UK, Canada and UN, such as the U.S. Treasury Department's Specially Designated Nationals List or the U.S. Commerce Department's Denied Persons List, Unverified List, or Entity List; or (ii) you intend to supply any Services to, or for the benefit of any natural or legal person that is located or resident in, Cuba, Iran, North Korea, Sudan or Syria, the Crimea, Sevastopol, Luhansk and Donetsk regions of Ukraine or any other jurisdiction subject to United States embargo (or a national or resident of one of these countries), or to a person listed on any sanctions asset blocking list or export denial list maintained by the US, EU, UK, Canada and UN, such as the Specially Designated Nationals List, Denied Persons List, Unverified List, or Entity List.</li>
</ol>
<ol start="11">
    <li><strong>Termination</strong>. We may suspend or terminate your access to and use of the Services, at our sole discretion, at any time and without notice to you. Upon any termination, discontinuation or cancellation of your access to the Services, the following Sections will survive: III, IV, V, VI, VII, VIII, IX, X, XI, XII, XIII, XIV, XV, XVI, XVII, and XVIII.</li>
</ol>
<ol start="12">
    <li>
        <p><strong>Risk Disclosures; Disclaimers</strong>. THE SERVICES BEING PROVIDED ARE UNDER ONGOING DEVELOPMENT AND ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. We make no warranty that the Services, including for the avoidance of doubt, the association of Human Readable Names to SuiNS Protocol names, will meet your requirements, will be accurate and operational when desired, will function as intended, will be free from bugs or errors, or be available on an uninterrupted, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness or reliability of any information or content on the Services. We operate the Services for convenience purposes only, and make no warranty regarding the software or any contents contained in the Move package referenced by the Human Readable Name, and it is solely up to you to maintain the contents of such Move package, including any updated versions of such software.</p>
        <p>Access to the Services, the Move Registry, and the SuiNS Protocol is provided as-is, and users engage with it at their own risk. The Foundation and its associated entities disclaim any liability for the operation of the Services, the Move Registry, and the SuiNS Protocol, including but not limited to issues such as failed transactions, inaccuracies, loss of funds, or technical malfunctions. You acknowledge that you fully understand that the any decentralized blockchain, including any content, smart contract or information contained therein, operates without the possibility of intervention by the Foundation. By accessing or using the Services, you agree not to hold the Foundation, its affiliates, and each of their employees, directors, officers, agents, representatives, or any of its service providers liable for any losses, damages, or costs incurred as a result of your use of the Services. You expressly acknowledge that no developer or entity involved in creating or offering the Services will be liable for any claims or damages whatsoever related to your use, inability to use, or interaction with other users of the Services.&nbsp;</p>
        <p>You understand the inherent risks associated with using cryptographic and blockchain-based systems, and you represent and warrant that you have a working knowledge of the usage and intricacies of digital assets and networks such as Sui, the SuiNS Protocol, the Move Registry, the Sui token, the SNS token, and other digital assets. In particular, you understand that blockchain-based transactions are irreversible and we have no control over the functioning of the Sui blockchain, the SuiNS Protocol and their associated ecosystems, and neither we nor any of our agents or representatives shall be liable for any issues arising therefrom.</p>
        <p>You understand and acknowledge that cryptography is a progressing field with advances in code cracking and other technical advancements, which may present risks to your digital assets, name registrations, the associated Move packages, and the Services, and could result in the theft or loss of your digital assets, name registrations, and the associated Move packages. We do not make any binding commitment or guarantee or otherwise ensure full security of the Services. We cannot guarantee that the Services, the Move Registry, the SuiNS Protocol or the Sui blockchain protocol will not become the victim of unauthorized access. To the extent this occurs, your funds may be irrevocably lost or locked.&nbsp;</p>
        <p>YOU ACCEPT ALL RISKS ASSOCIATED WITH THE USE OF THE SERVICES TO CONDUCT TRANSACTIONS, INCLUDING, BUT NOT LIMITED TO, THE FAILURE OF HARDWARE, SOFTWARE, INTERNET CONNECTIONS, AND FAILURES RELATED TO ANY SUPPORTED NETWORK. THE NATURE OF DIGITAL ASSETS MEANS THAT ANY TECHNOLOGICAL DIFFICULTIES EXPERIENCED BY THE SUI BLOCKCHAIN PROTOCOL, THE SUINS PROTOCOL OR THE MOVE REGISTRY MAY PREVENT THE ACCESS OR USE OF YOUR DIGITAL ASSETS, NAME REGISTRATIONS, OR THE ASSOCIATED MOVE PACKAGES. WE ARE NOT RESPONSIBLE FOR ANY UNAUTHORIZED ACCESS OR LOSS OR HARM AN UNAUTHORIZED ACCESS MAY CAUSE, UNLESS CAUSED BY OUR WILLFUL MISCONDUCT.&nbsp;</p>
    </li>
    <li><strong>Indemnity</strong>. You will indemnify and hold the Foundation, its service providers, its their affiliates and its and their officers, directors, employees and agents (collectively, the “<u>Covered Parties</u>”) harmless from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (a) your access to or use of the Services, (b) your Linked Content, or (c) your violation of these Terms.</li>
</ol>
<ol start="14">
    <li><strong> Limitation of Liability</strong>.<ol>
            <li>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NO COVERED PARTY WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY COVERED PARTY HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</li>
            <li>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE COVERED PARTIES’ TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES EXCEED THE AMOUNTS YOU HAVE PAID OR ARE PAYABLE BY YOU TO THE FOUNDATION FOR USE OF THE SERVICES OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO THE FOUNDATION, AS APPLICABLE.</li>
            <li>THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN THE FOUNDATION AND ALL THIRD-PARTY COVERED PARTIES ARE EXPRESS THIRD-PARTY BENEFICIARIES OF SECTIONS XIII AND XIV HEREIN.</li>
        </ol>
    </li>
</ol>
<ol start="15">
    <li><strong>Governing Law and Forum Choic</strong>e. These Terms are governed by and shall be construed and enforced under the Laws of the Cayman Islands without regard to or application of any choice or conflict of laws, rules or principles. </li>
</ol>
<ol start="16">
    <li><strong>Dispute Resolution</strong>.<ol>
            <li>If a dispute arises out of or relates to these Terms, including the existence, validity, interpretation, performance, breach or termination hereof or any dispute regarding non-contractual obligations arising out of or relating to these Terms shall be referred to and finally resolved by binding arbitration administered by the Cayman Islands International Arbitration Centre (CIAC) and governed by the Arbitration Act (as amended) of the Cayman Islands. The arbitration shall be conducted in the English language and the place of arbitration shall be in George Town, Grand Cayman, Cayman Islands. The number of arbitrators shall be one. The decision of the sole arbitrator to any such dispute, controversy, difference or claim shall be final and binding upon both parties and judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction. If any proceeding is brought for the enforcement of these Terms, then the successful or substantially prevailing party shall be entitled to recover attorneys’ fees and other costs incurred in such proceeding in addition to any other relief to which it may be entitled. You and we each waive any right to assert the doctrine of forum non conveniens, to assert that you or we are not subject to the jurisdiction of such arbitration or courts or to object to venue to the extent any proceeding is brough in accordance herewith. </li>
            <li><u>Class Action Waiver</u>. YOU AGREE THAT YOU MAY BRING CLAIMS AGAINST THE FOUNDATION IN YOUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, if the parties’ dispute is resolved through arbitration, the arbitrator may not consolidate another person’s claims with your claims, and may not otherwise preside over any form of a representative or class proceeding. If this specific provision is found to be unenforceable, then the entirety of this Dispute Resolution section shall be null and void.</li>
            <li><u>Severability</u>. With the exception of any of the provisions in Section XVI(B) of these Terms (“<u>Class Action Waiver</u>”), if an arbitrator or court of competent jurisdiction decides that any part of these Terms is invalid or unenforceable, the other parts of these Terms will still apply.</li>
        </ol>
    </li>
</ol>
<ol start="17">
    <li><strong>General Terms</strong>.<ol>
            <li><u>Reservation of Rights</u>. The Foundation and its licensors exclusively own all right, title and interest in and to the Services, including all associated intellectual property rights. You acknowledge that the Services are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services.</li>
            <li><u>Entire Agreement</u>. These Terms constitute the entire and exclusive understanding and agreement between the Foundation and you regarding the Services, and these Terms supersede and replace all prior oral or written understandings or agreements between the Foundation and you regarding the Services. If any provision of these Terms is held invalid or unenforceable by an arbitrator or a court of competent jurisdiction, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect. Except where provided by applicable law in your jurisdiction, you may not assign or transfer these Terms, by operation of law or otherwise, without the Foundation’s prior written consent. Any attempt by you to assign or transfer these Terms absent our consent or your statutory right, without such consent, will be null. The Foundation may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</li>
            <li><u>Separate Written Agreements</u>. We may require you to enter into separate written agreements to use the Website. In such cases, these Terms should be read in conjunction with the separate agreements, but in the event of any conflict or inconsistency, the written agreements will prevail.</li>
            <li><u>Notices</u>. Any notices or other communications provided by the Foundation under these Terms will be given: (i) via email; or (ii) by posting to the Services. For notices made by email, the date of receipt will be deemed the date on which such notice is transmitted.</li>
            <li><u>Waiver of Rights</u>. The Foundation’s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of the Foundation. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</li>
        </ol>
    </li>
</ol>
<ol start="18">
    <li><strong>Contact Information</strong>. If you have any questions about these Terms or the Services, please contact the Foundation at legal@mystenlabs.com</li>
</ol>`;

export default function Terms() {
  return (
    <PlainPageLayout>
        <div id="terms" dangerouslySetInnerHTML={{__html: TERMS_CONTENT}} />
    </PlainPageLayout>
  );
}
